services:
  postgres:
    # DATABASE_URL=postgresql://postgres:password@localhost:5432/myapp
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network


volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
