GET http://localhost:3333/

###

POST http://localhost:3333/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get courses
GET http://localhost:3333/courses?search=React&limit=10&offset=0
Content-Type: application/json

### Create a new course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de React Native",
  "description": ""
}

### Get a course by id
GET http://localhost:3333/courses/43e6f7d8-eeb9-482e-bfd0-ae53edd7c636

### Login
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Lorenzo53@gmail.com",
  "password": "123123"
}

###
