### Get courses
GET http://localhost:3333/courses?search=React&limit=10&offset=0
Content-Type: application/json

### Create a new course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de React Native",
  "description": "Curso de React Native"
}

### Get a course by id
GET http://localhost:3333/courses/025eab12-1380-4821-acf2-0ee67a08929b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2Y1ZTQ3NC0yMTUyLTQxM2QtYTZiNi01N2RhMGMyYzM5Y2UiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjY1OTU1OH0.oRyrNVglNy5xX2K76XsuzL6zTDF2xnndX-rZ-rsSoDo

### Login
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Lorenzo53@gmail.com",
  "password": "123123"
}

###
