GET http://localhost:3333/

###

POST http://localhost:3333/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

###
GET http://localhost:3333/courses

###
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de React Native",
  "description": ""
}

###
GET http://localhost:3333/courses/43e6f7d8-eeb9-482e-bfd0-ae53edd7c636